---
title: "figuremaking"
author: "julien"
date: "25 Sep 2015"
output:
  pdf_document:
    keep_tex: true
    fig_caption: true
    
---


```{r, include=FALSE, cache=FALSE}
# here we get the data and the plots

source("Mastercode.r")
```



```{r,  echo=FALSE ,fig.cap= " \\label{fig:PKC} Failed attempts to identify the PKC gene involved in operant self-learning. Performance indexes (PI) during a test period following an 8 min. training session is reported. LEFT: Flies putatively mutants for PKC genes (PKC-53e, PKC-delta and PCK-InaC) performed well in the self-learning assay. RIGHT: Flies with RNAi constructs targeting PKC53e and PKC InaC were crossed to elav-Gal4;tub-Gal80ts or to CS females. RNAi was induced for two days before the experiment via a 32&deg; heat-shock. While the construct targeting PKC InaC had no effect, the construct for PKC53e prevented self-learning formation even in absence of Gal4 driven expression, such that no firm conclusions can be drawn. Full genotype of the flies tested is indicated below.  CS  x 53eRi_V : ;;UAS_PKC53eRNAi_27696/+ . elavG4;tG80  x  PKC53eRi_V : elavGal4/+;tubGal80ts/+;UAS_PKC53eRNAI_27696/+ . elavG4;tG80  x  PKCInacRi : elavGal4/+;tubGal80ts/+;UAS_PKCInacRNAI_2895/+. Data is shown as Tukey's boxplots (median is the line surrounded by boxes representing quartiles) with a superposed violinplot. Asterisks indicate significant difference of the score against 0, using a non-parametrical Wilcox test."}

plot_grid(P_1, P_2, labels=c("A", "B","C","D"), ncol = 2, nrow = 2)
```

```{r, echo=FALSE, fig.cap= "\\label{fig:heatshock} PKC inhibition (achieved by using an effective heat-shock protocol) in neurons, but not central brain regions, prevents self-learning formation. Driving Gal4 in all neurons using the elav-Gal4 driver while inactivating its ubiquitously expressed inhibitor Gal80 with a heat-shock induces the expression of the PKC inhibitor. While test flies are still performing well after a mild heat-shock (A, data pooled from different protocols: 33&deg; for 15h, 36&deg; for 2h, and 37&deg; for 1h),  a strong heat-shock prevents learning in control flies (B, 37&deg; for 2h). After a 4-hour heat-shock at 35&deg;C, test but not control flies were unable to form self-learning (C). Using this latter protocol, we restricted the expression of Gal4 in central brain regions using different drivers targeting central brain regions (D), which were all ineffective in preventing self-learning. Full genotype of the flies tested is indicated below.  elavG4  xCS : elav-Gal4/+ . elavG4  x T_PKCi : elav-Gal4/+;tubGal80ts/+ ; UAS-PKCi/+ . CS  x T_PKCi : tubGal80ts/+ ; UAS-PKCi/+. 7y;c819G4  x T_PKCi : tubGal80ts/+ ; UAS-PKCi/+ __ H24-Gal4 . c232G4  x T_PKCi : tubGal80ts/+ ; UAS-PKCi/7y_Gal4,c819-Gal4 . H24G4  x T_PKCi : tubGal80ts/+ ; UAS-PKCi/c232-Gal4. Data is shown as Tukey's boxplots (median is the line surrounded by boxes representing quartiles) with a superposed violinplot. Asterisks indicate significant difference of the score against 0, using a non-parametrical Wilcox test."}

plot_grid(P_4, P_5, P_6, P_7, labels=c("A", "B","C","D"), ncol = 2, nrow = 2)
```


```{r, echo=FALSE, fig.cap= "\\label{fig:motoneurons} Flies with PKCi expression in motorneurons, are impaired in self-learning. A. Using OK371-Gal4 (expression in most glutamatergic neurons) or d42-Gal4 to drive PKCi expression was effective in preventing self-learning, while the control flies seem to learn, although the score of the d42Gal4 x CS control line was not statistically significantly positive. B. While the previous result with the D42Gal4 driver was reproduced, using c380-Gal4, a second driver showing expression in motorneurons, yielded comparable results. C. The use of the d42Gal4,chaGal80 double construct as a driver was effective in preventing self-learning, while the controls did perform well. Heat-shock protocol was a 4-hour heat-shock at 35&deg;C. Full genotype of the flies tested is indicated below.  CS  x T_PKCi : tubGal80ts/+ ; UAS-PKCi/+ . d42G4  x T_PKCi : tubGal80ts/+ ; UAS-PKCi/d42-Gal4 . OK371G4  x T_PKCi : tubGal80ts/+ ; UAS-PKCi/+;OK371/+ . d42G4  x CS : d42Gal4/+ . OK371  x CS : OK371/+ .c380G4  x T_PKCi : c380-Gal4/+ . c380G4  x CS : c380Gal4/+; tubGal80ts/+ ; UAS-PKCi/+ . d42G4,chaG80  x CS : d42-Gal4, cha-Gal80/+ . d42G4,chaG80  x T_PKCi : tubGal80ts/+ ; UAS-PKCi/d42-Gal4, cha-Gal80 . CS  x T_PKCi : tubGal80ts/+ ; UAS-PKCi/+. Data is shown as Tukey's boxplots (median is the line surrounded by boxes representing quartiles) with a superposed violinplot. Asterisks indicate significant difference of the score against 0, using a non-parametrical Wilcox test."}

plot_grid(P_8, P_9, P_10, labels=c("A", "B","C","D"), ncol = 2, nrow = 2)
```




